// Pure helpers for the mouse-angle widget: parse/format the generated
// ~/.config/hypr/mouse-angle.lua table, angle formatting, device filtering.

var ANGLE_RE = /name\s*=\s*"([^"]+)"\s*,\s*rotation\s*=\s*(\d+)/g
// Video/keyboard nodes that Hyprland also lists under "mice".
var NODE_RE = /consumer-control|-keyboard/
// Key codes live in 64-bit words, printed highest word first: the last word
// holds bits 0-63, i.e. letters/digits for keyboards. Mice keep those clear.
var NODES_MARKER = "===NODES==="

function normalize(deg) {
  var n = Math.round(Number(deg))
  if (!isFinite(n)) return 0
  n = n % 360
  return n < 0 ? n + 360 : n
}

// Hyprland normalizes device names to lowercase with dashes; anything else
// would break the generated Lua string, so refuse it.
function isSafeName(name) {
  return /^[a-z0-9()_.-]+$/.test(String(name || ""))
}

function parseAngleFile(text) {
  var out = [], seen = {}, m
  ANGLE_RE.lastIndex = 0
  while ((m = ANGLE_RE.exec(String(text || ""))) !== null) {
    if (seen[m[1]] || !isSafeName(m[1])) continue
    seen[m[1]] = true
    out.push({ name: m[1], rotation: normalize(parseInt(m[2], 10)) })
  }
  return out
}

function formatAngleFile(entries) {
  var lines = [
    "-- Mouse rotation (sensor angle) per device. Generated by the",
    "-- omarchy-mouse-angle bar widget; edit it there, or by hand followed",
    "-- by `hyprctl reload`. Degrees are clockwise: 353 == 7 anticlockwise.",
    ""
  ]
  for (var i = 0; i < (entries || []).length; i++) {
    var e = entries[i]
    if (!e || !isSafeName(e.name)) continue
    lines.push('hl.device({ name = "' + e.name + '", rotation = ' + normalize(e.rotation) + ' })')
  }
  return lines.join("\n") + "\n"
}

function find(entries, name) {
  for (var i = 0; i < (entries || []).length; i++)
    if (entries[i].name === name) return entries[i]
  return null
}

function upsert(entries, name, deg) {
  var out = [], hit = false
  for (var i = 0; i < (entries || []).length; i++) {
    if (entries[i].name === name) { out.push({ name: name, rotation: normalize(deg) }); hit = true }
    else out.push(entries[i])
  }
  if (!hit) out.push({ name: name, rotation: normalize(deg) })
  return out
}

// 0..359 clockwise -> signed degrees, which is how people think about it.
function signed(deg) {
  var n = normalize(deg)
  return n > 180 ? n - 360 : n
}

function label(deg) {
  var n = signed(deg)
  if (n === 0) return "0\u00b0"
  return (n > 0 ? "+" : "-") + Math.abs(n) + "\u00b0"
}

function describe(deg) {
  var n = signed(deg)
  if (n === 0) return "no rotation"
  return Math.abs(n) + "\u00b0 " + (n > 0 ? "clockwise" : "anticlockwise")
}

function parseMice(json) {
  var out = []
  var data
  try { data = JSON.parse(String(json || "")) } catch (e) { return out }
  var mice = (data && data.mice) || []
  for (var i = 0; i < mice.length; i++) {
    var name = mice[i] && mice[i].name
    if (!name || NODE_RE.test(name) || out.indexOf(name) !== -1) continue
    out.push(name)
  }
  return out
}

function normalizeName(name) {
  return String(name || "").trim().toLowerCase().replace(/\s+/g, "-")
}

function isKeyboardNode(keyMask) {
  var tokens = String(keyMask || "").trim().split(/\s+/)
  if (!tokens[tokens.length - 1]) return false
  var low = parseInt(tokens[tokens.length - 1], 16)
  return isFinite(low) && low > 1
}

// A node named "<product> Mouse" belongs to that product's keyboard when a
// keyboard node exists under the base name - e.g. "Wooting Wooting 60HE (ARM)
// Mouse" next to keyboard node "Wooting Wooting 60HE (ARM)". A standalone
// mouse like "Finalmouse UltralightX dongle Mouse" has no such base node.
function isKeyboardEmbedded(name, keyboards) {
  var m = String(name || "").match(/^(.*)-mouse(?:-\d+)?$/)
  return !!(m && keyboards[m[1]])
}

// listProc output: `hyprctl devices -j`, a marker line, then one
// "name<TAB>key mask" line per /sys/class/input/event* node.
function parseDeviceDump(raw) {
  var text = String(raw || "")
  var at = text.indexOf(NODES_MARKER)
  var micePart = at === -1 ? text : text.slice(0, at)
  var nodesPart = at === -1 ? "" : text.slice(at + NODES_MARKER.length)

  var keyboards = {}
  var lines = nodesPart.split("\n")
  for (var i = 0; i < lines.length; i++) {
    var tab = lines[i].lastIndexOf("\t")
    if (tab <= 0) continue
    var kname = normalizeName(lines[i].slice(0, tab))
    if (kname && isKeyboardNode(lines[i].slice(tab + 1))) keyboards[kname] = true
  }

  var out = []
  var mice = parseMice(micePart)
  for (var j = 0; j < mice.length; j++)
    if (!isKeyboardEmbedded(mice[j], keyboards)) out.push(mice[j])
  return out
}

// "endgame-gear-endgame-gear-op1-8k-v2-gaming-mouse" -> "Endgame Gear OP1 8k v2 Gaming"
function prettyName(name) {
  var words = String(name || "").split("-")
  if (words.length > 3 && words[words.length - 1] === "mouse") words.pop()
  // Composite HID devices repeat the vendor: "endgame gear endgame gear ..."
  if (words.length >= 4 && words[0] === words[2] && words[1] === words[3]) words = words.slice(2)
  else if (words.length >= 3 && words[0] === words[1]) words.shift()
  for (var i = 0; i < words.length; i++) {
    var w = words[i]
    if (/^\d/.test(w) || w === "v2") continue
    words[i] = w.charAt(0).toUpperCase() + w.slice(1)
  }
  return words.join(" ")
}
