// Pure helpers for the mouse-angle widget: parse/format the generated
// ~/.config/hypr/mouse-angle.lua table, angle formatting, device filtering.
//
// Settings are keyed by a mouse's hardware id - evdev "bustype:vendor:product"
// plus its serial when the node reports one - not by device name. Hyprland's
// hl.device only matches by name, so each entry also carries the last known
// device name; the widget re-heals that name whenever the hardware id shows
// up under a different one.

var ANGLE_RE = /name\s*=\s*"([^"]+)"\s*,\s*rotation\s*=\s*(\d+)/
var HWID_RE = /--\s*hwid\s*([^\s]+)/
// Video/keyboard nodes that Hyprland also lists under "mice".
var NODE_RE = /consumer-control|-keyboard/
// Key codes live in 64-bit words, printed highest word first: the last word
// holds bits 0-63, i.e. letters/digits for keyboards. Mice keep those clear.
var NODES_MARKER = "===NODES==="

function normalize(deg) {
  var n = Math.round(Number(deg))
  if (!isFinite(n)) return 0
  n = n % 360
  return n < 0 ? n + 360 : n
}

// Hyprland normalizes device names to lowercase with dashes; anything else
// would break the generated Lua string, so refuse it.
function isSafeName(name) {
  return /^[a-z0-9()_.-]+$/.test(String(name || ""))
}

// "0003:361d:100:AB12" -> "0003:361d:0100:ab12"; null when malformed.
function normalizeHwid(raw) {
  var parts = String(raw || "").toLowerCase().split(":")
  var out = [], i
  if (parts.length !== 3 && parts.length !== 4) return null
  for (i = 0; i < 3; i++) {
    if (!/^[0-9a-f]{1,4}$/.test(parts[i])) return null
    out.push(("000" + parseInt(parts[i], 16).toString(16)).slice(-4))
  }
  if (parts.length === 4) {
    if (!/^[0-9a-z]{1,32}$/.test(parts[3])) return null
    out.push(parts[3])
  }
  return out.join(":")
}

function isSafeHwid(hw) {
  return /^[0-9a-f]{4}(:[0-9a-f]{4}){2}(:[0-9a-z]{1,32})?$/.test(String(hw || ""))
}

// Identity key of a device or a stored entry. hwid beats name; names cannot
// contain ":", so the two key spaces never collide.
function keyOf(e) {
  return (e && e.hwid) || (e && e.name) || ""
}

function parseAngleFile(text) {
  var out = [], seen = {}, lines = String(text || "").split("\n"), i, m, h, e
  for (i = 0; i < lines.length; i++) {
    m = ANGLE_RE.exec(lines[i])
    if (!m) continue
    h = HWID_RE.exec(lines[i])
    e = { hwid: normalizeHwid(h ? h[1] : null), name: m[1], rotation: normalize(parseInt(m[2], 10)) }
    if (seen[keyOf(e)] || !isSafeName(e.name)) continue
    seen[keyOf(e)] = true
    out.push(e)
  }
  return out
}

function formatAngleFile(entries) {
  var lines = [
    "-- Mouse rotation (sensor angle) per device. Generated by the",
    "-- omarchy-mouse-angle bar widget; edit it there, or by hand followed",
    "-- by `hyprctl reload`. Degrees are clockwise: 353 == 7 anticlockwise.",
    "-- A mouse is identified by the trailing -- hwid bus:vendor:product[:serial];",
    "-- the name is only Hyprland's handle for applying it at startup.",
    ""
  ]
  for (var i = 0; i < (entries || []).length; i++) {
    var e = entries[i]
    if (!e || !isSafeName(e.name)) continue
    lines.push('hl.device({ name = "' + e.name + '", rotation = ' + normalize(e.rotation) + ' })' +
      (isSafeHwid(e.hwid) ? " -- hwid " + e.hwid : ""))
  }
  return lines.join("\n") + "\n"
}

function find(entries, key) {
  for (var i = 0; i < (entries || []).length; i++)
    if (keyOf(entries[i]) === key) return entries[i]
  return null
}

function upsert(entries, entry) {
  var out = [], hit = false, key = keyOf(entry)
  for (var i = 0; i < (entries || []).length; i++) {
    if (keyOf(entries[i]) === key) { out.push(entry); hit = true }
    else out.push(entries[i])
  }
  if (!hit) out.push(entry)
  return out
}

// 0..359 clockwise -> signed degrees, which is how people think about it.
function signed(deg) {
  var n = normalize(deg)
  return n > 180 ? n - 360 : n
}

function label(deg) {
  var n = signed(deg)
  if (n === 0) return "0\u00b0"
  return (n > 0 ? "+" : "-") + Math.abs(n) + "\u00b0"
}

function describe(deg) {
  var n = signed(deg)
  if (n === 0) return "no rotation"
  return Math.abs(n) + "\u00b0 " + (n > 0 ? "clockwise" : "anticlockwise")
}

function parseMice(json) {
  var out = []
  var data
  try { data = JSON.parse(String(json || "")) } catch (e) { return out }
  var mice = (data && data.mice) || []
  for (var i = 0; i < mice.length; i++) {
    var name = mice[i] && mice[i].name
    if (!name || NODE_RE.test(name) || out.indexOf(name) !== -1) continue
    out.push(name)
  }
  return out
}

function normalizeName(name) {
  return String(name || "").trim().toLowerCase().replace(/\s+/g, "-")
}

function isKeyboardNode(keyMask) {
  var tokens = String(keyMask || "").trim().split(/\s+/)
  if (!tokens[tokens.length - 1]) return false
  var low = parseInt(tokens[tokens.length - 1], 16)
  return isFinite(low) && low > 1
}

// A node named "<product> Mouse" belongs to that product's keyboard when a
// keyboard node exists under the base name - e.g. "Wooting Wooting 60HE (ARM)
// Mouse" next to keyboard node "Wooting Wooting 60HE (ARM)". A standalone
// mouse like "Finalmouse UltralightX dongle Mouse" has no such base node.
function isKeyboardEmbedded(name, keyboards) {
  var m = String(name || "").match(/^(.*)-mouse(?:-\d+)?$/)
  return !!(m && keyboards[m[1]])
}

// hyprctl device name -> sysfs node hwid. Hyprland dedups name collisions
// with "-N" suffixes and composite HID devices repeat the vendor ("endgame
// gear endgame gear ..."), so try the exact name, the dedup-stripped base,
// and a "-<node name>" suffix before giving up (null = key by name).
function matchHwid(m, nodes) {
  var bases = [m], dm = m.match(/^(.*)-mouse-\d+$/)
  if (dm) bases.push(dm[1])
  var b, i, C, N
  for (b = 0; b < bases.length; b++) {
    C = bases[b]
    for (i = 0; i < nodes.length; i++) {
      N = nodes[i].name
      if (C === N || C === N + "-mouse" || N === C + "-mouse") return nodes[i].hwid
    }
  }
  for (b = 0; b < bases.length; b++) {
    C = bases[b]
    for (i = 0; i < nodes.length; i++) {
      N = nodes[i].name
      if (C.length > N.length && C.slice(-(N.length + 1)) === "-" + N) return nodes[i].hwid
    }
  }
  return null
}

// listProc output: `hyprctl devices -j`, a marker line, then one
// "name<TAB>key mask<TAB>bustype:vendor:product[:serial]" line per
// /sys/class/input/event* node (the id column is absent when unreadable).
function parseDeviceDump(raw) {
  var text = String(raw || "")
  var at = text.indexOf(NODES_MARKER)
  var micePart = at === -1 ? text : text.slice(0, at)
  var nodesPart = at === -1 ? "" : text.slice(at + NODES_MARKER.length)

  var keyboards = {}, nodes = []
  var lines = nodesPart.split("\n")
  for (var i = 0; i < lines.length; i++) {
    var parts = lines[i].split("\t")
    var nname = normalizeName(parts[0])
    if (!nname) continue
    if (parts.length >= 2 && isKeyboardNode(parts[1])) keyboards[nname] = true
    nodes.push({ name: nname, hwid: parts.length >= 3 ? normalizeHwid(parts[2]) : null })
  }

  var mice = parseMice(micePart), out = []
  for (var j = 0; j < mice.length; j++)
    if (!isKeyboardEmbedded(mice[j], keyboards))
      out.push({ name: mice[j], hwid: matchHwid(mice[j], nodes) })
  return out
}

// "endgame-gear-endgame-gear-op1-8k-v2-gaming-mouse" -> "Endgame Gear OP1 8k v2 Gaming"
function prettyName(name) {
  var words = String(name || "").split("-")
  if (words.length > 3 && words[words.length - 1] === "mouse") words.pop()
  // Composite HID devices repeat the vendor: "endgame gear endgame gear ..."
  if (words.length >= 4 && words[0] === words[2] && words[1] === words[3]) words = words.slice(2)
  else if (words.length >= 3 && words[0] === words[1]) words.shift()
  for (var i = 0; i < words.length; i++) {
    var w = words[i]
    if (/^\d/.test(w) || w === "v2") continue
    words[i] = w.charAt(0).toUpperCase() + w.slice(1)
  }
  return words.join(" ")
}
